version: "3"
services:
  washer:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=carwasher
      - POSTGRES_USER=carwasher
      - POSTGRES_PASSWORD=4221
    ports:
      - 5432:5432
#    volumes:
#      - db-data:/var/lib/postgresql/data